---
title: "Group Project_Jose"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(arrow)
```

## Open data file

I'm going to load the data I saved after the last exercise.
```{r load-data}

applications <- read_feather("C:/Users/jmqui/McGill University/Jose_Group - People Analytics/app_data_starter.feather")

# lists all variables (columns) in the data
applications |> tbl_vars()
```
```{r WG column creation}
library(tidyverse)

# Assuming your data frame is named "applications"
applications <- applications %>%
  mutate(WG = substr(examiner_art_unit, 1, 3))
# Print the table with the new column
print(applications)

# The "WG" column now contains the first three digits of "examiner_art_unit"
```

## Excel Excercise

For each TC let's count the number of individuals in each gender category

```{r rough dataset}
GroupProject<-applications %>%
  filter(disposal_type %in% c("ISS", "ABN")) %>%
  select(filing_date, appl_status_date,tenure_days, appl_status_code,disposal_type,gender, race, WG, examiner_art_unit, examiner_id, tc) %>%
  mutate(Status_Date = as.Date(appl_status_date, format = "%d%b%Y %H:%M:%S")) %>%
  mutate(Processing_Days = as.numeric(Status_Date - filing_date))
  # mutate(Processing_Speed = ifelse(Processing_Days <= 2000, "Fast",ifelse(Processing_Days <= 4000, "Regular", "Slow")))

```

```{r clean the dataset}
dataset <- GroupProject %>%
  # changed variable name 
  rename(id=examiner_id, status_date = Status_Date, processing_days = Processing_Days, wg = WG, art_unit = examiner_art_unit) %>%
  # created a new table with selected variables
  select(id, gender, race, disposal_type, status_date, filing_date, processing_days, tc, wg, art_unit, tenure_days ) %>%
  # drop all NAs for gender 
  drop_na(gender)%>%
  drop_na(processing_days)
```

```{r processing time of female and male in organizaion level by histogram}
average_gender_matrix_organization <- dataset %>%
  group_by(disposal_type, gender) %>%
  summarize(average_processing_days_gender = mean(processing_days, na.rm = TRUE)) %>%
  pivot_wider(names_from = disposal_type, values_from = average_processing_days_gender)

# Convert the matrix to a long format
average_gender_matrix_organization_long <- average_gender_matrix_organization %>%
  gather(disposal_type, average_processing_days_gender, -gender)

# Create the bar chart
bar_chart <- ggplot(average_gender_matrix_organization_long, aes(x = gender, y = average_processing_days_gender, fill = disposal_type)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Processing Time by Gender Across Organization",
       x = "Gender",
       y = "Average Processing Days",
       fill = "Disposal Type")

bar_chart
```

```{r processing time of race in organization level by histogram}
average_race_matrix_organization <- dataset %>%
  group_by(disposal_type, race) %>%
  summarize(average_processing_days_race = mean(processing_days, na.rm = TRUE)) %>%
  pivot_wider(names_from = disposal_type, values_from = average_processing_days_race)

# Convert the matrix to a long format
average_race_matrix_organization_long <- average_race_matrix_organization %>%
  gather(disposal_type, average_processing_days_race, -race)

# Create the bar chart
bar_chart_2 <- ggplot(average_race_matrix_organization_long, aes(x = race, y = average_processing_days_race, fill = disposal_type)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Processing Time by Race Across Organization",
       x = "Race",
       y = "Average Processing Days",
       fill = "Disposal Type")

bar_chart_2
```
```




# ```{r gender distribution}
# 
# applications %>% 
#    mutate(Processing_Speed = case_when(Processing_Days <= 2000 ~ "Fast",Processing_Days > 2000 & Processing_Days <= 4000 ~ "Regular",Processing_Days > 4000 ~ "Slow"))
# ```

